app:
  title: Scaffolded Backstage App
  #baseUrl: http://192.168.29.223:3000
  baseUrl: http://localhost:3000

organization:
  name: Aditya-711

backend:
  # Used for enabling authentication, secret is shared by all backend plugins
  # See https://backstage.io/docs/auth/service-to-service-auth for
  # information on the format
  auth:
    dangerouslyDisableDefaultAuthPolicy: true
  baseUrl: http://localhost:7007
  #baseUrl: http://192.168.29.223:7007
  listen:
    host: 0.0.0.0
    port: 7007
    # Uncomment the following host directive to bind to specific interfaces
    # host: 127.0.0.1
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
    # Default Helmet Content-Security-Policy values can be removed by setting the key to false
  cors: 
    #origin: http://192.168.29.223:3000
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'

integrations:
  github:
    - host: github.com
      token: 
  


techdocs:
  builder: 'local'
  generator:
    runIn: 'docker'
  publisher:
    type: 'local'

auth:
  environment: development
  providers:
    github:
      development:
        clientId: Ov23liv38BR3zE6d6ziuJ
        clientSecret: 18d63772181f50bd1cbb8b1623d8bd596a9590ddb
        enterpriseInstanceUrl: # This can be omitted for github.com
        signIn:
          enabled: true
          resolvers:
            - resolver: usernameMatchingUserEntityName
              source: github
              config:
                match:
                  - type: 'url'
                    pattern: 'https://github.com/Aditya-711'
    guest: {}
    bitbucket:
      development:
        clientId: # Add your Bitbucket OAuth client ID
        clientSecret: # Add your Bitbucket OAuth client secret
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName

scaffolder:
  # see https://backstage.io/docs/features/software-templates/configuration for software template options
  github:
    visibility: public # or 'private', 'internal'
    allowedOwners: ['ZensarIDP', 'Abhi232003','Aditya-711'] # ZensarIDP org and Abhi232003 user

  secrets:
    github:
      token: ${GITHUB_TOKEN}

  

  
  defaultAuthor:
    name: Backstage Scaffolder
    email: scaffolder@backstage.io
  defaultCommitMessage: 'Initial commit'

catalog:
  processingInterval: {seconds: 5}
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location, Template]
  locations:
    # Local example data, file locations are relative to the backend process, typically `packages/backend`
    - type: file
      target: ../../examples/entities.yaml

    # Templates
    - type: file
      target: ../../templates/aws-s3-provisioner/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ../../templates/aws-ec2-provisioner/template.yaml
      rules:
        - allow: [Template]

    - type: file
      target: ../../templates/aws-ec2-scripts-executer/template.yaml
      rules:
        - allow: [Template]

    - type: file
      target: ../../templates/aws-iam-provisioner/template.yaml
      rules:
        - allow: [Template]

    - type: file
      target: ../../templates/*/template.yaml
      rules:
        - allow: [Template]

    - type: file
      target: ../../packages/backend/templates/*/template.yaml
      rules:
        - allow: [Template]

    # Local example organizational data
    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]

    # GitHub organization discovery - discovers all repositories in your GitHub org
    # Temporarily disabled until GithubDiscoveryProcessor is properly configured
    # - type: github-discovery
    #   target: https://github.com/ZensarIDP

    # GitHub specific repository discovery - discovers specific repositories
    # Add your repository URLs here
    # - type: url
    #   target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all.yaml
    # - type: url
    #   target: https://github.com/ZensarIDP/backstage-idp/blob/main/catalog-info.yaml
    # - type: url
    #   target: https://github.com/Aditya-711/backstage_ssa_workflows

    
  # Enable real-time processing
  incremental:
    enabled: true
    # Force immediate processing
    pollingIntervalMs: 1000
    
# Add backend processing configuration

  csp:
    # Allow cache control
    directives:
      'Cache-Control': 'no-cache, no-store, must-revalidate'
# see https://backstage.io/docs/permissions/getting-started for more on the permission framework
permission:
  # setting this to `false` will disable permissions
  enabled: true

