---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
---
# GitHub User - Add your GitHub username here
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Aditya-711
  annotations:
    github.com/user-login: Aditya-711
spec:
  profile:
    displayName: Aditya-711
  memberOf: [developers]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []
---
# Developers group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: developers
spec:
  type: team
  children: []
